### ISSUE TITLE
ACNH 1.6 - Bot not providing customization options for update items. 

### ISSUE THREAD

**Issue by klutch5398** [kwsch/SysBot.AnimalCrossing#6]
The bot currently is not spitting out customization options for the new 1.6 Update Items. 

Here is the screenshot of the command not working from the latest build. 
I also updated the command list I made for the possible item customizations. Not sure if you actually need it anyway, but it's here. 

[acnh 1.6 command list.txt](https://github.com/kwsch/SysBot.AnimalCrossing/files/5598669/acnh.1.6.command.list.txt)

![item customization](https://user-images.githubusercontent.com/69431446/100269310-56694600-2f24-11eb-9e80-d6fe904e621b.png)
![nhse customizes](https://user-images.githubusercontent.com/69431446/100269312-56694600-2f24-11eb-9c1b-d07281773b2c.jpg)

**Comment by kwsch** [comment]
dll from NHSE has yet to be copied over
